// automatically generated by the FlatBuffers compiler, do not modifymodule import std.typecons;
module rpcgenerate.greeter.GreeterRequestFb;
import flatbuffers;


struct GreeterRequestFb {
	mixin Table!GreeterRequestFb;

  static GreeterRequestFb getRootAsGreeterRequestFb(ByteBuffer _bb) {  return GreeterRequestFb.init_(_bb.get!int(_bb.position()) + _bb.position(), _bb); }
	@property Nullable!string msg() { uint o = __offset(4); return o != 0 ? Nullable!string(__string(o + _pos)) : Nullable!string.init; }

	static uint createGreeterRequestFb(FlatBufferBuilder builder,uint msg) {
		builder.startObject(1);
		GreeterRequestFb.addMsg(builder, msg);
		return GreeterRequestFb.endGreeterRequestFb(builder);
	}

	static void startGreeterRequestFb(FlatBufferBuilder builder) { builder.startObject(1); }
	static void addMsg(FlatBufferBuilder builder, uint msgOffset) { builder.addOffset(0, msgOffset, 0); }
	static uint endGreeterRequestFb(FlatBufferBuilder builder) {
		uint o = builder.endObject();
		return o;
	}
}

