// Copyright (c) 2013-2015 Sandstorm Development Group, Inc. and contributors
// Licensed under the MIT License:
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

/**
 * <a href="https://capnproto.org">Cap'n Proto</a> is a highly efficient binary data format and
 * remote procedure call protocol.
 *
 * This package contains the runtime library to support code generated by capnpc-dlang, a schema
 * compiler plugin written in C++. It does not support RPC.
 *
 */
module capnproto;

public import capnproto.AnyPointer;
public import capnproto.Arena;
public import capnproto.ArrayInputStream;
public import capnproto.ArrayOutputStream;
public import capnproto.BufferedInputStream;
public import capnproto.BufferedInputStreamWrapper;
public import capnproto.BufferedOutputStream;
public import capnproto.BufferedOutputStreamWrapper;
public import capnproto.BuilderArena;
public import capnproto.Constants;
public import capnproto.Data;
public import capnproto.DataList;
public import capnproto.DecodeException;
public import capnproto.ElementSize;
public import capnproto.EnumList;
public import capnproto.FarPointer;
public import capnproto.FileDescriptor;
public import capnproto.GeneratedClassSupport;
public import capnproto.ListBuilder;
public import capnproto.ListList;
public import capnproto.ListPointer;
public import capnproto.ListReader;
public import capnproto.MemoryMapped;
public import capnproto.MessageBuilder;
public import capnproto.MessageReader;
public import capnproto.PackedInputStream;
public import capnproto.PackedOutputStream;
public import capnproto.PrimitiveList;
public import capnproto.ReaderArena;
public import capnproto.ReaderOptions;
public import capnproto.SegmentBuilder;
public import capnproto.SegmentReader;
public import capnproto.Serialize;
public import capnproto.SerializePacked;
public import capnproto.StructBuilder;
public import capnproto.StructList;
public import capnproto.StructPointer;
public import capnproto.StructReader;
public import capnproto.StructSize;
public import capnproto.Text;
public import capnproto.TextList;
public import capnproto.Void;
public import capnproto.WireHelpers;
public import capnproto.WirePointer;
