// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: test-import.capnp

#ifndef CAPNP_INCLUDED_d693321951fee8f3_
#define CAPNP_INCLUDED_d693321951fee8f3_

#include <capnp/generated-header-support.h>

#if CAPNP_VERSION != 6000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif

#include "test.capnp.h"

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(ce44e75b93239b3c);

}  // namespace schemas
}  // namespace capnp


struct Foo {
  Foo() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(ce44e75b93239b3c, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand = &schema->defaultBrand;
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class Foo::Reader {
public:
  typedef Foo Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand);
  }
#endif  // !CAPNP_LITE

  inline bool hasImportedStruct() const;
  inline  ::TestAllTypes::Reader getImportedStruct() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Foo::Builder {
public:
  typedef Foo Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasImportedStruct();
  inline  ::TestAllTypes::Builder getImportedStruct();
  inline void setImportedStruct( ::TestAllTypes::Reader value);
  inline  ::TestAllTypes::Builder initImportedStruct();
  inline void adoptImportedStruct(::capnp::Orphan< ::TestAllTypes>&& value);
  inline ::capnp::Orphan< ::TestAllTypes> disownImportedStruct();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Foo::Pipeline {
public:
  typedef Foo Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline  ::TestAllTypes::Pipeline getImportedStruct();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline bool Foo::Reader::hasImportedStruct() const {
  return !_reader.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline bool Foo::Builder::hasImportedStruct() {
  return !_builder.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline  ::TestAllTypes::Reader Foo::Reader::getImportedStruct() const {
  return ::capnp::_::PointerHelpers< ::TestAllTypes>::get(
      _reader.getPointerField(0 * ::capnp::POINTERS));
}
inline  ::TestAllTypes::Builder Foo::Builder::getImportedStruct() {
  return ::capnp::_::PointerHelpers< ::TestAllTypes>::get(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}
#if !CAPNP_LITE
inline  ::TestAllTypes::Pipeline Foo::Pipeline::getImportedStruct() {
  return  ::TestAllTypes::Pipeline(_typeless.getPointerField(0));
}
#endif  // !CAPNP_LITE
inline void Foo::Builder::setImportedStruct( ::TestAllTypes::Reader value) {
  ::capnp::_::PointerHelpers< ::TestAllTypes>::set(
      _builder.getPointerField(0 * ::capnp::POINTERS), value);
}
inline  ::TestAllTypes::Builder Foo::Builder::initImportedStruct() {
  return ::capnp::_::PointerHelpers< ::TestAllTypes>::init(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}
inline void Foo::Builder::adoptImportedStruct(
    ::capnp::Orphan< ::TestAllTypes>&& value) {
  ::capnp::_::PointerHelpers< ::TestAllTypes>::adopt(
      _builder.getPointerField(0 * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::TestAllTypes> Foo::Builder::disownImportedStruct() {
  return ::capnp::_::PointerHelpers< ::TestAllTypes>::disown(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}


#endif  // CAPNP_INCLUDED_d693321951fee8f3_
