// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: test-import.capnp

#include "test-import.capnp.h"

namespace capnp {
namespace schemas {
static const ::capnp::_::AlignedData<33> b_ce44e75b93239b3c = {
  {   0,   0,   0,   0,   5,   0,   6,   0,
     60, 155,  35, 147,  91, 231,  68, 206,
     18,   0,   0,   0,   1,   0,   0,   0,
    243, 232, 254,  81,  25,  50, 147, 214,
      1,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 178,   0,   0,   0,
     29,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     25,   0,   0,   0,  63,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    116, 101, 115, 116,  45, 105, 109, 112,
    111, 114, 116,  46,  99,  97, 112, 110,
    112,  58,  70, 111, 111,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
      4,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     13,   0,   0,   0, 122,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     12,   0,   0,   0,   3,   0,   1,   0,
     24,   0,   0,   0,   2,   0,   1,   0,
    105, 109, 112, 111, 114, 116, 101, 100,
     83, 116, 114, 117,  99, 116,   0,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
    167,   0, 177,  20,  23,  74, 175, 160,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     16,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_ce44e75b93239b3c = b_ce44e75b93239b3c.words;
#if !CAPNP_LITE
static const ::capnp::_::RawSchema* const d_ce44e75b93239b3c[] = {
  &s_a0af4a1714b100a7,
};
static const uint16_t m_ce44e75b93239b3c[] = {0};
static const uint16_t i_ce44e75b93239b3c[] = {0};
const ::capnp::_::RawSchema s_ce44e75b93239b3c = {
  0xce44e75b93239b3c, b_ce44e75b93239b3c.words, 33, d_ce44e75b93239b3c, m_ce44e75b93239b3c,
  1, 1, i_ce44e75b93239b3c, nullptr, nullptr, { &s_ce44e75b93239b3c, nullptr, nullptr, 0, 0, nullptr }
};
#endif  // !CAPNP_LITE
}  // namespace schemas
}  // namespace capnp

// =======================================================================================


// Foo
constexpr uint16_t Foo::_capnpPrivate::dataWordSize;
constexpr uint16_t Foo::_capnpPrivate::pointerCount;
#if !CAPNP_LITE
constexpr ::capnp::Kind Foo::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Foo::_capnpPrivate::schema;
constexpr ::capnp::_::RawBrandedSchema const* Foo::_capnpPrivate::brand;
#endif  // !CAPNP_LITE



